name: viterium_wallet
description: Viterium - a Non-Custodial Wallet for Vite Blockchain.
publish_to: "none"

version: 1.4.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 9.0.0
  shared_preferences: 2.2.3
  web_socket_channel: 2.4.5
  package_info_plus: 8.0.0
  device_info_plus: 10.1.0
  json_annotation: 4.8.1
  intl: 0.18.1
  decimal: 2.3.3
  rational: 2.2.2
  logger: 1.3.0
  hive_flutter: 1.1.0
  path_provider: 2.1.3
  local_auth: 2.2.0
  qr_flutter: 4.1.0
  qr_code_scanner: 1.0.1
  share_plus: 9.0.0
  file_picker: 8.0.2
  app_links: 4.0.1
  http: 1.2.1
  flutter_vibrate: 1.3.0
  flutter_slidable: 0.6.0
  validators: 3.0.0
  auto_size_text: 3.0.0
  url_launcher: 6.2.6
  devicelocale: 0.7.1
  flutter_riverpod: 2.5.1
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  freezed_annotation: 2.4.1
  json_converter: 2.0.0
  fast_immutable_collections: 10.2.2
  extended_image: 8.2.0
  vite:
    path: ../vite_dart
  viteconnect: 0.0.2
  #google_fonts: ^2.3.2
  cupertino_icons: 1.0.8
  oktoast: 3.4.0
  automatic_animated_list: 1.1.0
  lazy_load_scrollview: 1.3.0
  image_picker: 1.1.0
  barcode_finder: 0.0.5
  flutter_displaymode: 0.6.0
  push: 2.1.0
  crypton: 2.2.1
  flutter_portal: 1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  json_serializable: 6.7.1
  flutter_lints: 3.0.2
  freezed: 2.5.2
  flutter_launcher_icons: 0.13.1

# Flutter launcher icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: AppIconsCustom
      fonts:
        - asset: fonts/AppIconsCustom.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/token_icons/
    - assets/

  uses-material-design: true

scripts:
  codegen: dart run build_runner build --delete-conflicting-outputs
