/// Flutter icons AppIconsCustom
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconsCustom
///      fonts:
///       - asset: fonts/AppIconsCustom.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIconsCustom {
  AppIconsCustom._();

  static const _kFontFam = 'AppIconsCustom';
  static const String? _kFontPkg = null;

  static const IconData defi =
      IconData(0xf260, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
